# This file contains a storage pool over the ssd storage cluster.
# The pool below is replicated over both SSDs, without replication to another host

# This is developed against k8s 1.13.4 and rook stable 0.9.3

######################################
# Ceph-Pools                         #
######################################

apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  failureDomain: {{ .Values.storage.failureDomain }}
  replicated:
    size: {{ .Values.storage.replicaCount }}

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ .Release.Name }}
provisioner: ceph.rook.io/block
parameters:
  blockPool: {{ .Release.Name }}
  # Specify the namespace of the rook cluster from which to create volumes.
  # If not specified, it will use `rook` as the default namespace of the cluster.
  # This is also the namespace where the cluster will be
  clusterNamespace: {{ .Release.Namespace }}
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: {{ .Values.storage.fileSystem}}